#!/usr/bin/env bash
# Command script to run PingPong performance testing on multiple machines as MPI task on Azure Batch.
# Usage: application-cmd [nodes]

# For more details of MPI/RDMA, visit: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/rdma-cluster

# Use the Intel MPI exists in CentOS-HPC 7.6 image:
source /opt/intel/impi/2019.7.217/intel64/bin/mpivars.sh
# Prepare environment variables for Intel MPI to use RDMA on HB120_v2:
export FI_PROVIDER=verbs
export I_MPI_FABRICS=shm:ofi
export I_MPI_DEBUG=5
export I_MPI_FALLBACK_DEVICE=0 

# Debugging:
echo '---------------------------------------------------------'
env
echo '---------------------------------------------------------'

# Run MPI application with appropriate parameters:
set -x
mpirun -n $1 -ppn 1 -hosts $AZ_BATCH_HOST_LIST IMB-MPI1
set +x
