#!/usr/bin/env bash
# Command script to run PingPong performance testing on multiple machines as MPI task on Azure Batch.
# Usage: coordination-cmd

# For more details of MPI/RDMA, visit: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/rdma-cluster

# Prepare environment (e.g.: dynamically-created shared storage)
